### ISSUE TITLE
Hub Analytics

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-analytics#3]
## Goal

Users have access to mint analytics using cube.js.

## Requirements
- Time series graph of mints segmented by wallet, collection and project.

**Comment by mpwsh** [comment]
Previous hub-analytics repo has been migrated to [hub-analytics-go](https://github.com/holaplex/hub-analytics-go)

started new [consumer app](https://github.com/holaplex/hub-analytics) which has its own database, where different events will be saved and then read by [Cube](https://cube.dev.holaplex.tools/)

[hub-analytics chart](https://github.com/holaplex/helm-charts/tree/main/charts/hub-analytics) updated and deployed on staging, ArgoCD app [is in place](https://github.com/holaplex/hub-kubes/tree/main/analytics/stage) as well.

Deployed Cube into staging -added as dependency of the analytics chart-.
Migrated some data into it from our current databases to get some data to work with:

<img width="824" alt="image" src="https://github.com/holaplex/hub-analytics/assets/13471075/54dcb1c2-baa0-435c-ac41-bca475fe8d6c">


This data can be retrieved using graphql using the query
```graphql
query CubeQuery  { 
  cube(where: {wallets: {timestamp: {inDateRange: "This quarter" } }}) {
    wallets(orderBy: {count: desc}) {
      count
      blockchain
      timestamp {
        day
      }
    }
    projects {
      name
    }
  }
}

```

**Comment by mpwsh** [comment]
graphql Server pr:
https://github.com/holaplex/hub-analytics/pull/5

working on proposed changes
